### ISSUE TITLE
Pending invitation for @blackgirlbytes

### ISSUE THREAD

**Issue by blackgirlbytes** [derek-botany/invitation#6]

**Comment by rizel-test-user** [comment]
@blackgirlbytes has been added as a member of this repository. Please check your email or notifications for an invitation.

**Comment by rizel-test-user** [comment]
@blackgirlbytes is already a member of this repository.

**Comment by rizel-test-user** [comment]
@blackgirlbytes is already a member of this repository.

**Comment by rizel-test-user** [comment]
@blackgirlbytes has been added as a member of this repository. Please check your email or notifications for an invitation.

**Comment by rizel-test-user** [comment]
@blackgirlbytes is already a member of this repository.
